export const DEGREE_OF_KINSHIP = [
  { name: 'Pai/Mãe', value: 'parents' },
  { name: 'Filho/Filha', value: 'children' },
  { name: 'Marido/Esposa', value: 'husband' },
  { name: 'Nomorado/Namorada', value: 'lover' },
];

export const DAY_CARD_PROPS = [
  { title: 'Dia 01', description: '16/12/2024', active: true },
  { title: 'Dia 02', description: '17/12/2024', active: true },
  { title: 'Dia 03', description: '18/12/2024', active: true },
  { title: 'Dia 04', description: '19/12/2024', active: true },
  { title: 'Dia 05', description: '20/12/2024', active: true },
];

export const INDUSTRY = [
  { description: 'pedertractor', active: true },
  { description: 'tractor', active: true },
];

export const SECTOR_LIST = [
  {
    name: 'SOLDA MONTAGEM ROBOTIZADA B2',
    value: 'SOLDA_MONTAGEM_ROBOTIZADA_B2',
  },
  { name: 'E-COAT', value: 'E-COAT' },
  { name: 'CONFORMAÇÃO A1', value: 'CONFORMACAO_A1' },
  { name: 'APRENDIZ', value: 'APRENDIZ' },
  { name: 'PRENSA', value: 'PRENSA' },
  { name: 'SOLDA DIVERSOS B1', value: 'SOLDA_DIVERSOS_B1' },
  { name: 'LABORATORIO QUIMICO', value: 'LABORATORIO_QUIMICO' },
  { name: 'SOLDA DIVERSOS B3', value: 'SOLDA_DIVERSOS_B3' },
  { name: 'LAVADOR', value: 'LAVADOR' },
  { name: 'SOLDA DIVERSOS A1', value: 'SOLDA_DIVERSOS_A1' },
  { name: 'SERRALHERIA', value: 'SERRALHERIA' },
  { name: 'PINTURA ELETROSTATICA', value: 'PINTURA_ELETROSTATICA' },
  {
    name: 'LOGISTICA PREPARAÇÃO PARA EXPEDIÇÃO',
    value: 'LOGISTICA_PREPARACAO_PARA_EXPEDICAO',
  },
  { name: 'PINTURA LIQUIDA', value: 'PINTURA_LIQUIDA' },
  { name: 'LOGISTICA ABASTECIMENTO', value: 'LOGISTICA_ABASTECIMENTO' },
  { name: 'DOBRA TUBO', value: 'DOBRA_TUBO' },
  { name: 'SOLDA DIVERSOS A2.1', value: 'SOLDA_DIVERSOS_A2.1' },
  { name: 'ESTOQUE DE COMPONENTES A', value: 'ESTOQUE_DE_COMPONENTES_A' },
  { name: 'MANUTENÇÃO PREDIAL', value: 'MANUTENCAO_PREDIAL' },
  {
    name: 'DESENVOLVIMENTO DE PROCESSOS',
    value: 'DESENVOLVIMENTO_DE_PROCESSOS',
  },
  { name: 'SEIS SIGMA', value: 'SEIS_SIGMA' },
  { name: 'MONTAGEM', value: 'MONTAGEM' },
  { name: 'MANUTENÇÃO PRODUÇÃO', value: 'MANUTENCAO_PRODUCAO' },
  { name: 'CALANDRA', value: 'CALANDRA' },
  { name: 'SOLDA DIVERSOS A2.3', value: 'SOLDA_DIVERSOS_A2.3' },
  { name: 'COMPRAS', value: 'COMPRAS' },
  { name: 'TORNEARIA CNC', value: 'TORNEARIA_CNC' },
  { name: 'LOGÍSTICA MOVIMENTAÇÃO', value: 'LOGISTICA_MOVIMENTACAO' },
  { name: 'SOLDA ROBOTIZADA B2', value: 'SOLDA_ROBOTIZADA_B2' },
  { name: 'ANALISE E PLANEJAMENTO', value: 'ANALISE_E_PLANEJAMENTO' },
  { name: 'POLIMENTO GERAL', value: 'POLIMENTO_GERAL' },
  { name: 'SEGURANÇA DO TRABALHO', value: 'SEGURANCA_DO_TRABALHO' },
  { name: 'LASER', value: 'LASER' },
  { name: 'MANUTENÇÃO ELETRICA', value: 'MANUTENCAO_ELETRICA' },
  { name: 'QUALIDADE CLIENTE', value: 'QUALIDADE_CLIENTE' },
  { name: 'SERRA CORTE', value: 'SERRA_CORTE' },
  { name: 'SOLDA ESTRUTURAL C1', value: 'SOLDA_ESTRUTURAL_C1' },
  { name: 'REBARBA CORTE', value: 'REBARBA_CORTE' },
  {
    name: 'PRE TRATAMENTO SUPERFICIE (BANHO)',
    value: 'PRE_TRATAMENTO_SUPERFICIE_BANHO',
  },
  { name: 'LIMPEZA INDUSTRIAL', value: 'LIMPEZA_INDUSTRIAL' },
  { name: 'SOLDA DIVERSOS A2.2', value: 'SOLDA_DIVERSOS_A2.2' },
  { name: 'PLASMA', value: 'PLASMA' },
  { name: 'SEGURANÇA PATRIMONIAL', value: 'SEGURANCA_PATRIMONIAL' },
  { name: 'AUTOMAÇÃO INDUSTRIAL', value: 'AUTOMACAO_INDUSTRIAL' },
  { name: 'GERENCIA DE PRODUÇÃO', value: 'GERENCIA_DE_PRODUCAO' },
  { name: 'PLASMA 3D', value: 'PLASMA_3D' },
  { name: 'CENTRO DE USINAGEM CNC', value: 'CENTRO_DE_USINAGEM_CNC' },
  { name: 'SOLDA ESTRUTURAL D1', value: 'SOLDA_ESTRUTURAL_D1' },
  { name: 'ACABAMENTO GERAL', value: 'ACABAMENTO_GERAL' },
  { name: 'COTAÇÃO', value: 'COTACAO' },
  { name: 'EXPEDIÇÃO', value: 'EXPEDICAO' },
  { name: 'DIRETORIA', value: 'DIRETORIA' },
  { name: 'PUNCIONADEIRA', value: 'PUNCIONADEIRA' },
  { name: 'QUALIDADE PRODUÇÃO', value: 'QUALIDADE_PRODUCAO' },
  { name: 'ACABAMENTO SOLDA', value: 'ACABAMENTO_SOLDA' },
  { name: 'SOLDA ESTRUTURAL B2', value: 'SOLDA_ESTRUTURAL_B2' },
  { name: 'CONTABILIDADE', value: 'CONTABILIDADE' },
  { name: 'CORTE', value: 'CORTE' },
  { name: 'FERRAMENTARIA', value: 'FERRAMENTARIA' },
  { name: 'USINAGEM', value: 'USINAGEM' },
  { name: 'MANUTENÇÃO ELETROMECANICA', value: 'MANUTENCAO_ELETROMECANICA' },
  { name: 'RECEBIMENTO', value: 'RECEBIMENTO' },
  { name: 'OXICORTE', value: 'OXICORTE' },
  { name: 'DEPARTAMENTO PESSOAL', value: 'DEPARTAMENTO_PESSOAL' },
  {
    name: 'DESENVOLVIMENTO DE FERRAMENTAL',
    value: 'DESENVOLVIMENTO_DE_FERRAMENTAL',
  },
  { name: 'ENCHIMENTO', value: 'ENCHIMENTO' },
  { name: 'PCP', value: 'PCP' },
  { name: 'TREINAMENTO E QUALIFICAÇÃO', value: 'TREINAMENTO_E_QUALIFICACAO' },
  { name: 'DESENVOLVIMENTO', value: 'DESENVOLVIMENTO' },
  {
    name: 'JATO DE GRANALHA ESTACIONARIO',
    value: 'JATO_DE_GRANALHA_ESTACIONARIO',
  },
  { name: 'SOLDA', value: 'SOLDA' },
  { name: 'ESTOQUE', value: 'ESTOQUE' },
  { name: 'ALMOXARIFADO GERAL', value: 'ALMOXARIFADO_GERAL' },
  { name: 'MEDICINA OCUPACIONAL', value: 'MEDICINA_OCUPACIONAL' },
  { name: 'USINAGEM CONVENCIONAL', value: 'USINAGEM_CONVENCIONAL' },
  { name: 'GERENCIA DE QUALIDADE', value: 'GERENCIA_DE_QUALIDADE' },
  { name: 'DESENVOLVIMENTO AMOSTRAS', value: 'DESENVOLVIMENTO_AMOSTRAS' },
  { name: 'CONSTRUÇÃO CIVIL', value: 'CONSTRUCAO_CIVIL' },
  { name: 'CALANDRA GRANDE', value: 'CALANDRA_GRANDE' },
  { name: 'ALMOXARIFADO QUIMICO', value: 'ALMOXARIFADO_QUIMICO' },
  {
    name: 'TI - TECNOLOGIA DA INFORMAÇÃO',
    value: 'TI_TECNOLOGIA_DA_INFORMACAO',
  },
  { name: 'BORDONADEIRA', value: 'BORDONADEIRA' },
  { name: 'GERENCIA DE COMPRAS', value: 'GERENCIA_DE_COMPRAS' },
  { name: 'JATO DE GRANALHA AUTOMATICO', value: 'JATO_DE_GRANALHA_AUTOMATICO' },
  {
    name: 'ESTAÇÃO DE TRAT. DE EFLUENTES (ETE)',
    value: 'ESTACAO_DE_TRAT_DE_EFLUENTES_ETE',
  },
  { name: 'SOLDA PRISIONEIRO', value: 'SOLDA_PRISIONEIRO' },
  { name: 'GERENCIA DE CONTROLADORIA', value: 'GERENCIA_DE_CONTROLADORIA' },
  { name: 'GERENCIA COMERCIAL', value: 'GERENCIA_COMERCIAL' },
  { name: 'CONTROLADORIA', value: 'CONTROLADORIA' },
  { name: 'SOLDA TESTE ESTANQUEIDADE', value: 'SOLDA_TESTE_ESTANQUEIDADE' },
  { name: 'GERENCIA DE PLANEJAMENTO', value: 'GERENCIA_DE_PLANEJAMENTO' },
  { name: 'PREPARAÇÃO', value: 'PREPARACAO' },
  { name: 'FINANCEIRO', value: 'FINANCEIRO' },
  { name: 'PROCESSO QUALIDADE', value: 'PROCESSO_QUALIDADE' },
  { name: 'SOLDA PONTO', value: 'SOLDA_PONTO' },
  { name: 'PRENSA GRANDE', value: 'PRENSA_GRANDE' },
  {
    name: 'GERENCIA DE RECURSOS HUMANOS',
    value: 'GERENCIA_DE_RECURSOS_HUMANOS',
  },
  {
    name: 'MANUTENÇÃO HIDRAULICA / PNEUMATICA',
    value: 'MANUTENCAO_HIDRAULICA_PNEUMATICA',
  },
  { name: 'RECURSOS HUMANOS', value: 'RECURSOS_HUMANOS' },
  { name: 'CALANDRA TUBO / PERFIL', value: 'CALANDRA_TUBO_PERFIL' },
  { name: 'ESTOQUE DE COMPONENTE A', value: 'ESTOQUE_DE_COMPONENTE_A' },
  {
    name: 'PRE TRATAMENTO SUPERFIE (BANHO)',
    value: 'PRE_TRATAMENTO_SUPERFIE_BANHO',
  },
  { name: 'SGI', value: 'SGI' },
  {
    name: 'SOLDA TESTE DE ESTANQUEIDADE',
    value: 'SOLDA_TESTE_DE_ESTANQUEIDADE',
  },
  { name: 'GERENCIA FINANCEIRA', value: 'GERENCIA_FINANCEIRA' },
  { name: 'ENGENHARIA MECANICA', value: 'ENGENHARIA_MECANICA' },
];
